### ISSUE TITLE
Make build fails

### ISSUE THREAD

**Issue by wins2on** [fivosts/llvmTools#4]
I'm having trouble building the llvmTools. I use llvm version 9. Error trace is below.

jev@jev:~/foivos/build$ make 
Scanning dependencies of target hello
[ 10%] Building CXX object hello/CMakeFiles/hello.dir/hello.cpp.o
[ 20%] Linking CXX shared module libhello.so
[ 20%] Built target hello
Scanning dependencies of target BasicTechniques
[ 30%] Building CXX object BasicTechniques/CMakeFiles/BasicTechniques.dir/basicTechniques.cpp.o
[ 40%] Linking CXX shared module libBasicTechniques.so
[ 40%] Built target BasicTechniques
Scanning dependencies of target RuntimeRecorder
[ 50%] Building CXX object RuntimeRecorder/CMakeFiles/RuntimeRecorder.dir/RuntimeRecorder.cpp.o
[ 60%] Linking CXX shared module libRuntimeRecorder.so
[ 60%] Built target RuntimeRecorder
Scanning dependencies of target RuntimeTypeLib
[ 70%] Building CXX object RuntimeRecorder/RuntimeTypeLib/CMakeFiles/RuntimeTypeLib.dir/valueRecorder.cpp.o
In file included from /home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/function_call.h:1:0,
                 from /home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:4:
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/ir_type.h:185:7: error: using typedef-name ‘float_t’ after ‘class’
 class float_t : public ir_type{
       ^
In file included from /usr/include/math.h:45:0,
                 from /usr/include/c++/4.8/cmath:44,
                 from /usr/include/c++/4.8/random:38,
                 from /usr/include/c++/4.8/bits/stl_algo.h:65,
                 from /usr/include/c++/4.8/algorithm:62,
                 from /home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/ir_type.h:4,
                 from /home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/function_call.h:1,
                 from /home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:4:
/usr/include/x86_64-linux-gnu/bits/mathdef.h:28:15: note: ‘float_t’ has a previous declaration here
 typedef float float_t;  /* `float' expressions are evaluated as `float'.  */
               ^
In file included from /home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/function_call.h:1:0,
                 from /home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:4:
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/ir_type.h:199:7: error: using typedef-name ‘double_t’ after ‘class’
 class double_t : public ir_type{
       ^
In file included from /usr/include/math.h:45:0,
                 from /usr/include/c++/4.8/cmath:44,
                 from /usr/include/c++/4.8/random:38,
                 from /usr/include/c++/4.8/bits/stl_algo.h:65,
                 from /usr/include/c++/4.8/algorithm:62,
                 from /home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/ir_type.h:4,
                 from /home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/function_call.h:1,
                 from /home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:4:
/usr/include/x86_64-linux-gnu/bits/mathdef.h:29:16: note: ‘double_t’ has a previous declaration here
 typedef double double_t; /* `double' expressions are evaluated
                ^
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp: In function ‘void update_float(float, unsigned int, unsigned int)’:
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:278:51: error: no matching function for call to ‘std::vector<ir_type*>::push_back(float_t*)’
      global_variables.push_back(new float_t(value));
                                                   ^
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:278:51: note: candidates are:
In file included from /usr/include/c++/4.8/vector:64:0,
                 from /usr/include/c++/4.8/bits/random.h:34,
                 from /usr/include/c++/4.8/random:50,
                 from /usr/include/c++/4.8/bits/stl_algo.h:65,
                 from /usr/include/c++/4.8/algorithm:62,
                 from /home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/ir_type.h:4,
                 from /home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/function_call.h:1,
                 from /home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:4:
/usr/include/c++/4.8/bits/stl_vector.h:901:7: note: void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = ir_type*; _Alloc = std::allocator<ir_type*>; std::vector<_Tp, _Alloc>::value_type = ir_type*]
       push_back(const value_type& __x)
       ^
/usr/include/c++/4.8/bits/stl_vector.h:901:7: note:   no known conversion for argument 1 from ‘float_t* {aka float*}’ to ‘ir_type* const&’
/usr/include/c++/4.8/bits/stl_vector.h:919:7: note: void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = ir_type*; _Alloc = std::allocator<ir_type*>; std::vector<_Tp, _Alloc>::value_type = ir_type*]
       push_back(value_type&& __x)
       ^
/usr/include/c++/4.8/bits/stl_vector.h:919:7: note:   no known conversion for argument 1 from ‘float_t* {aka float*}’ to ‘ir_type*&&’
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:280:36: error: cannot convert ‘float_t* {aka float*}’ to ‘ir_type*’ in initialization
      ir_type *f = new float_t(value);
                                    ^
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:285:56: error: no matching function for call to ‘function_call::set_ret_value(float_t*)’
     func_calls[index]->set_ret_value(new float_t(value));
                                                        ^
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:285:56: note: candidate is:
In file included from /home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:4:0:
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/function_call.h:9:15: note: virtual void function_call::set_ret_value(ir_type*)
  virtual void set_ret_value(ir_type* ret) = 0;
               ^
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/function_call.h:9:15: note:   no known conversion for argument 1 from ‘float_t* {aka float*}’ to ‘ir_type*’
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:288:56: error: no matching function for call to ‘function_call::set_arg_value(float_t*)’
     func_calls[index]->set_arg_value(new float_t(value));
                                                        ^
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:288:56: note: candidate is:
In file included from /home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:4:0:
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/function_call.h:10:15: note: virtual void function_call::set_arg_value(ir_type*)
  virtual void set_arg_value(ir_type* ret){ (void) ret; }
               ^
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/function_call.h:10:15: note:   no known conversion for argument 1 from ‘float_t* {aka float*}’ to ‘ir_type*’
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp: In function ‘void update_double(double, unsigned int, unsigned int)’:
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:305:52: error: no matching function for call to ‘std::vector<ir_type*>::push_back(double_t*)’
      global_variables.push_back(new double_t(value));
                                                    ^
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:305:52: note: candidates are:
In file included from /usr/include/c++/4.8/vector:64:0,
                 from /usr/include/c++/4.8/bits/random.h:34,
                 from /usr/include/c++/4.8/random:50,
                 from /usr/include/c++/4.8/bits/stl_algo.h:65,
                 from /usr/include/c++/4.8/algorithm:62,
                 from /home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/ir_type.h:4,
                 from /home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/function_call.h:1,
                 from /home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:4:
/usr/include/c++/4.8/bits/stl_vector.h:901:7: note: void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = ir_type*; _Alloc = std::allocator<ir_type*>; std::vector<_Tp, _Alloc>::value_type = ir_type*]
       push_back(const value_type& __x)
       ^
/usr/include/c++/4.8/bits/stl_vector.h:901:7: note:   no known conversion for argument 1 from ‘double_t* {aka double*}’ to ‘ir_type* const&’
/usr/include/c++/4.8/bits/stl_vector.h:919:7: note: void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = ir_type*; _Alloc = std::allocator<ir_type*>; std::vector<_Tp, _Alloc>::value_type = ir_type*]
       push_back(value_type&& __x)
       ^
/usr/include/c++/4.8/bits/stl_vector.h:919:7: note:   no known conversion for argument 1 from ‘double_t* {aka double*}’ to ‘ir_type*&&’
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:307:37: error: cannot convert ‘double_t* {aka double*}’ to ‘ir_type*’ in initialization
      ir_type *d = new double_t(value);
                                     ^
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:312:57: error: no matching function for call to ‘function_call::set_ret_value(double_t*)’
     func_calls[index]->set_ret_value(new double_t(value));
                                                         ^
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:312:57: note: candidate is:
In file included from /home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:4:0:
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/function_call.h:9:15: note: virtual void function_call::set_ret_value(ir_type*)
  virtual void set_ret_value(ir_type* ret) = 0;
               ^
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/function_call.h:9:15: note:   no known conversion for argument 1 from ‘double_t* {aka double*}’ to ‘ir_type*’
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:315:57: error: no matching function for call to ‘function_call::set_arg_value(double_t*)’
     func_calls[index]->set_arg_value(new double_t(value));
                                                         ^
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:315:57: note: candidate is:
In file included from /home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/valueRecorder.cpp:4:0:
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/function_call.h:10:15: note: virtual void function_call::set_arg_value(ir_type*)
  virtual void set_arg_value(ir_type* ret){ (void) ret; }
               ^
/home/jev/foivos/llvmTools/RuntimeRecorder/RuntimeTypeLib/function_call.h:10:15: note:   no known conversion for argument 1 from ‘double_t* {aka double*}’ to ‘ir_type*’
make[2]: *** [RuntimeRecorder/RuntimeTypeLib/CMakeFiles/RuntimeTypeLib.dir/valueRecorder.cpp.o] Error 1
make[1]: *** [RuntimeRecorder/RuntimeTypeLib/CMakeFiles/RuntimeTypeLib.dir/all] Error 2
make: *** [all] Error 2

**Comment by fivosts** [comment]
Hi @wins2on, there must be some issue with your compiler version. Compilation with gcc-9 works fine for me.

In any case, as I'm refactoring the whole codebase at the moment and many things will not work, make sure you are using commit https://github.com/fivosts/llvmTools/commit/cce4312b914f8c192ea5bee888a861eac8f7c604

This is a good checkpoint for llvm-9. If it won't work (I'm reminding to you that I haven't checked that the llvm-9 compatible pass works) then you will use the exact same pass I am using with llvm-7.

**Comment by wins2on** [comment]
Alright, thank you!
